# Generated by Django 3.2.22 on 2023-10-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0003_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
