# Generated by Django 3.2.22 on 2023-10-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0006_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Pendiente'), ('I', 'Inciada'), ('F', 'Finalizada')], default='I', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
