# Generated by Django 3.2.22 on 2023-10-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0007_auto_20231012_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
