# Generated by Django 3.2.22 on 2023-10-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0011_equipos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectoss'},
        ),
    ]
