# Generated by Django 3.2.22 on 2023-10-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0013_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipos',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'equipos'},
        ),
    ]
